FlaskBlog/flaskblog/main/routes.py
from flask import render_template, request, Blueprint
from flaskblog.models import Post

# main is the name of package.
main = Blueprint('main', __name__)


# root route or home route
@main.route('/')
@main.route('/home', methods=['GET', 'POST'])
def home():
    # pagination 
    page = request.args.get('page', 1, type=int)

    # ordering the post in descending order of date_posted so as newest is at top
    posts = Post.query.order_by(Post.date_posted.desc()).paginate(page=page, per_page=4)
    return render_template('home.html', title='home-page', posts=posts)


# about page route
@main.route('/about', methods=['GET', 'POST'])
def about():
    return render_template('about.html', title='about-page')


# latest posts routes

@main.route('/latest_post')
def latest_post():
    # getting all the posts 
    posts = Post.query.order_by(Post.date_posted.desc())
    # reversing the posts so as to get the latest at top
    return render_template('latest_post.html', title='Latest-post', posts = posts)

# calendar route
@main.route('/calendar')
def calendar():
    # renders an html for a calendar element
    return render_template('calender.html', title='Calendar')

# annnouncement route
@main.route('/announcements')
def announcements():
    return render_template('announcements.html', title='Announcements')

FlaskBlog/flaskblog/posts/routes.py
# All imports required

import datetime
from flask import (render_template, url_for, flash,
                   redirect, request, abort, Blueprint)
from flask_login import current_user, login_required
from flaskblog import db
from flaskblog.models import Post
from flaskblog.posts.forms import PostForm

# Creating bluepring of posts
posts = Blueprint('posts', __name__)

# new_post route with GET and POST method and login_required decorator


@posts.route('/post/new', methods=['GET', 'POST'])
@login_required
def new_post():
    # instance of PostForm
    form = PostForm()  # to know how it works go to bottom of this page or go to https://blog.miguelgrinberg.com/post/the-flask-mega-tutorial-part-iii-web-forms

    # Validating the credentials of the form
    if form.validate_on_submit():
        post = Post(title=form.title.data,
                    content=form.content.data, author=current_user)
        # Saving the new post to the db
        db.session.add(post)
        db.session.commit()

        # Putting alert on the user end and a bootstrap success call
        flash('Your new Post has been created!', 'success')

        # redirecting back to homepage
        return redirect(url_for('main.home'))

    # if an invalid form re-render the html
    return render_template('create_post.html', title='New-Post', form=form, legend='New Post')


# post route
@posts.route('/post/<int:post_id>', methods=['GET', 'POST'])
# required an integer post_id
def post(post_id):
    # returns a post object having id of post as 'post_id'.
    post = Post.query.get_or_404(post_id)
    return render_template('post.html', title=post.title, post=post)

# update post route


@posts.route('/post/<int:post_id>/update', methods=['GET', 'POST'])
# required an integer post_id
def update_post(post_id):
    # returns a post object having id of post as 'post_id'.
    post = Post.query.get_or_404(post_id)

    # if not the user's post
    if post.author != current_user:
        # abort by returning 403
        abort(403)

    form = PostForm()
    # Validating the credentials of the form
    if form.validate_on_submit():
        # Saving changes to db
        post.title = form.title.data
        post.content = form.content.data
        post.date_posted = datetime.utcnow()
        db.session.commit()

        # alert for user
        flash('Your post has been updated!', 'success')
        return redirect(url_for('posts.post', post_id=post.id))

    # if the request is just 'GET' then just render the prev data in the form as it is
    elif request.method == 'GET':
        form.title.data = post.title
        form.content.data = post.content

    return render_template('create_post.html', title='Update-Post', form=form, legend='Update Post')

# delete_post route, login_required decorator


@posts.route('/post/<int:post_id>/delete', methods=['POST'])
@login_required
# needs an integer post_id
def delete_post(post_id):
    # gets the post or return 404 if not found
    post = Post.query.get_or_404(post_id)
    if post.author != current_user:
        # if user is not author return 403
        abort(403)

    # Removing the post after validation and saving changes to db
    db.session.delete(post)
    db.session.commit()

    flash('Your post has been deleted!', 'success')
    # redirecting to home again
    return redirect(url_for('main.home'))


'''
The first new thing in this version is the methods argument in the route decorator. This tells Flask that this view function accepts GET and POST requests, overriding the default, which is to accept only GET requests. The HTTP protocol states that GET requests are those that return information to the client (the web browser in this case). All the requests in the application so far are of this type. POST requests are typically used when the browser submits form data to the server (in reality GET requests can also be used for this purpose, but it is not a recommended practice). The "Method Not Allowed" error that the browser showed you before, appears because the browser tried to send a POST request and the application was not configured to accept it. By providing the methods argument, you are telling Flask which request methods should be accepted.

The form.validate_on_submit() method does all the form processing work. When the browser sends the GET request to receive the web page with the form, this method is going to return False, so in that case the function skips the if statement and goes directly to render the template in the last line of the function.

When the browser sends the POST request as a result of the user pressing the submit button, form.validate_on_submit() is going to gather all the data, run all the validators attached to fields, and if everything is all right it will return True, indicating that the data is valid and can be processed by the application. But if at least one field fails validation, then the function will return False, and that will cause the form to be rendered back to the user, like in the GET request case. Later I'm going to add an error message when validation fails.

When form.validate_on_submit() returns True, the login view function calls two new functions, imported from Flask. The flash() function is a useful way to show a message to the user. A lot of applications use this technique to let the user know if some action has been successful or not. In this case, I'm going to use this mechanism as a temporary solution, because I don't have all the infrastructure necessary to log users in for real yet. The best I can do for now is show a message that confirms that the application received the credentials.
'''

FlaskBlog/flaskblog/users/routes.py
# All imports

import os
from flask import (render_template, url_for, flash,
                   redirect, request, Blueprint, current_app)
from flask_login import login_user, current_user, logout_user, login_required
from flaskblog import db, bcrypt
from flaskblog.models import User, Post
from flaskblog.users.forms import (
    RegistrationForm, LoginForm, UpdateAccountForm, RequestResetForm, ResetPasswordForm)
from flaskblog.users.utils import save_picture, send_reset_email

# users is the name of package.
users = Blueprint('users', __name__)


@users.route("/register", methods=['GET', 'POST'])
def register():
    # is_authenticated
    # This property should return True if the user is authenticated, i.e. they have provided valid credentials. (Only authenticated users will fulfill the criteria of login_required.)

    # if user is login already then it can't register. So redirect it back to home
    if current_user.is_authenticated:
        return redirect(url_for('main.home'))
    # creating instance of RegistrationForm class
    form = RegistrationForm()

    # if form is submitted successfully
    if form.validate_on_submit():
        hashed_password = bcrypt.generate_password_hash(
            form.password.data).decode('utf-8')
        user = User(username=form.username.data,
                    email=form.email.data, password=hashed_password)
        db.session.add(user)
        db.session.commit()
        flash('Your account has been created! You are now able to log in', 'success')
        return redirect(url_for('users.login'))
    return render_template('register.html', title='Register', form=form)


@users.route('/login', methods=['GET', 'POST'])
def login():
    # if already one of the user is logged in then redirect it to home as there should be only one user logged in at a time.
    if current_user.is_authenticated:   # current_user is built in proxy for logged user. We can access logged in user using current_user
        return redirect(url_for('main.home'))

    form = LoginForm()
    # if the details provided by user satisfy the validation of each field (username, email, password, etc)
    if form.validate_on_submit():
        # it ret
        user = User.query.filter_by(email=form.email.data).first()

        if user and bcrypt.check_password_hash(user.password, form.password.data):
            login_user(user, remember=form.remember.data)

# request.args.next returns none if user is trying to move to another page directly from url section
# it is used here if user is not logged in then we need to render it to home page. We can't give him access to the requested url. Here this url is basically  localhost://account.html

# When the log in view is redirected to, it will have a next variable in the query string, which is the page that the user was trying to access.
            next_page = request.args.get('next')
            if next_page:
                return redirect(next_page)
            else:
                return redirect(url_for('main.home'))

        else:
            flash('Login Unsuccessful. Please check email and password', 'danger')
    return render_template('login.html', title='Login', form=form)


@users.route("/logout")
def logout():
    logout_user()
    return redirect(url_for('main.home'))


@users.route("/account", methods=['GET', 'POST'])
@login_required  # built in decorator available in flask which is used to check whether user is logged in or not
# it will work according to the login_view mentioned. It is mentioned as 'login' in __init__.py file
def account():
    form = UpdateAccountForm()
    if form.validate_on_submit():
        if form.picture.data:
            picture_file = save_picture(form.picture.data)
            if current_user.image_file != 'default.png':
                previous_picture_file = os.path.join(
                    current_app.root_path, 'static/profile_pics/', current_user.image_file
                )
            else:
                previous_picture_file = ''
            current_user.image_file = picture_file
            # deleting previous profile picture
            if previous_picture_file:
                os.remove(previous_picture_file)

        current_user.username = form.username.data
        current_user.email = form.email.data
        db.session.commit()
        flash('Your account has been updated!', 'success')
        return redirect(url_for('users.account'))

    # first time when user come to account route that time request is GET. So set the form data to the user data. So that it will be displayed to the user(as previous data) instead of blank data.
    elif request.method == 'GET':
        form.username.data = current_user.username
        form.email.data = current_user.email

    image_file = url_for(
        'static', filename='profile_pics/'+current_user.image_file)
    return render_template('account.html', title='Account', image_file=image_file, form=form)


@users.route('/user/<string:username>', methods=['GET', 'POST'])
def user_posts(username):
    page = request.args.get('page', 1, type=int)

    # getting the user object who is the author of post to which current user is trying to access
    user = User.query.filter_by(username=username).first_or_404()

# arranging the all posts of that author according to the posted time of each post.
    posts = Post.query.filter_by(author=user).order_by(
        Post.date_posted.desc()).paginate(page=page, per_page=4)
    return render_template('user_posts.html', posts=posts, user=user)


@users.route("/reset_password", methods=['GET', 'POST'])
def reset_request():
    # if already one of the user is logged in then redirect it to home as there should be only one user logged in at a time.
    if current_user.is_authenticated:
        return redirect(url_for('main.home'))
    form = RequestResetForm()
    if form.validate_on_submit():
        user = User.query.filter_by(email=form.email.data).first()
        send_reset_email(user)
        flash('An email has been sent with instructions to reset password', 'info')
        return redirect(url_for('users.login'))
    return render_template('reset_request.html', title='Reset-Password', form=form)


@users.route("/reset_password/<token>", methods=['GET', 'POST'])
def reset_token(token):
    if current_user.is_authenticated:
        return redirect(url_for('main.home'))
    user = User.verify_reset_token(token)
    if user is None:
        flash('That is an invalid or expired token', 'warning')
        return redirect(url_for('users.reset_request'))

    form = ResetPasswordForm()
    # if form is submitted successfully
    if form.validate_on_submit():
        hashed_password = bcrypt.generate_password_hash(
            form.password.data).decode('utf-8')

        user.password = hashed_password
        db.session.commit()
        flash('Your Password has been updated! You are now able to log in', 'success')
        return redirect(url_for('users.login'))
    return render_template('reset_token.html', title='Reset-token', form=form)


# delete account
@login_required
@users.route("/delete_account", methods=['GET', 'POST'])
def delete_account():
    user = current_user._get_current_object()
    posts = Post.query.filter_by(author=user).all()

    for post in posts:
        db.session.delete(post)
        db.session.commit()

    if user.image_file != "default.png":
        user_profile = os.path.join(current_app.root_path, 'static/profile_pics/', user.image_file)
        os.remove(user_profile)

    db.session.delete(user)
    db.session.commit()

    return redirect(url_for('main.home'))

FlaskBlog/flaskblog/templates/layout.html
<!DOCTYPE html>
<html>
  <head>
    <!-- Required meta tags -->
    <meta charset="utf-8" />
    <meta
      name="viewport"
      content="width=device-width, initial-scale=1, shrink-to-fit=no"
    />

    <!-- Bootstrap CSS -->
    <link
      rel="stylesheet"
      href="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0/css/bootstrap.min.css"
      integrity="sha384-Gn5384xqQ1aoWXA+058RXPxPg6fy4IWvTNh0E263XmFcJlSAwiGgFAW/dAiS6JXm"
      crossorigin="anonymous"
    />

    <link
      rel="stylesheet"
      type="text/css"
      href="{{ url_for('static', filename='main.css') }}"
    />
    <!-- Some custom styling for the page -->
    <style>
      #navbar-buttons {
        text-align: center;
      }
      #navbar-buttons button {
        margin: auto;
        padding: 0.1em;
        font-family: Verdana, Geneva, Tahoma, sans-serif;
        font-size: 1.2em;
        color: rgb(255, 255, 255);
        background-color: rgb(26, 152, 156);
        border: 0;
        border-radius: 0.3em;
        transition: all 0.2s ease-in;
      }

      #navbar-buttons button:hover {
        color: rgb(26, 152, 156);
        cursor: pointer;
        background-color: rgb(255, 255, 255);
        border-color: aqua;
        box-shadow: 0.5 0.5em 5em 0.5em #10dac9;
        /* transform: translateY(-0.1em); */
      }

      .list-group .list-group-item {
        border-bottom: 0.1;
      }

      .list-group .list-group-item:hover {
        box-shadow: 0.05em 0.05em 0.1em 0.1em rgb(24, 140, 144);
        transition: all 0.2s ease-out;
        transform: translateY(-0.1em);
      }

      .delete-account-btn{
        background-color:#ffffff;
        color: #d93116;;
        border-color: #d93116;
        border-radius: 0.3em;
        padding: 0.3em;
      }

      .delete-account-btn:hover{
        background-color: #d93116;;
        color: #ffffff;
        transform: translateY(-1px);
        box-shadow: 2px 2px 2px #ee5e47;
        transition: 0.4s all;
      }
      
    </style>
    <!-- check for the title passed from the route -->
    {% if title %}
    <title>Flask Blog - {{ title }}</title>
    {% else %}
    <title>Flask Blog</title>
    {% endif %}
  </head>

  <body style="background-color: rgb(240, 240, 240)">
    <header class="site-header">
      <nav
        class="navbar navbar-expand-md navbar-dark fixed-top"
        style="background-color: rgb(26, 152, 156)"
      >
        <div class="container">
          <!-- logo for the header flaskblog -->

          <svg
            xmlns="http://www.w3.org/2000/svg"
            width="30"
            height="35"
            fill="white"
            class="bi bi-chat-left-text-fill"
            viewBox="0 0 16 16"
          >
            <path
              d="M0 2a2 2 0 0 1 2-2h12a2 2 0 0 1 2 2v8a2 2 0 0 1-2 2H4.414a1 1 0 0 0-.707.293L.854 15.146A.5.5 0 0 1 0 14.793V2zm3.5 1a.5.5 0 0 0 0 1h9a.5.5 0 0 0 0-1h-9zm0 2.5a.5.5 0 0 0 0 1h9a.5.5 0 0 0 0-1h-9zm0 2.5a.5.5 0 0 0 0 1h5a.5.5 0 0 0 0-1h-5z"
            />
          </svg>

          <!-- link to homepage -->

          <a
            class="navbar-brand mr-4"
            style="
              font-size: 1.5em;
              color: rgb(255, 255, 255);
              margin-left: 0.5em;
            "
            href="{{ url_for('main.home')}}"
          >
            FlaskBlog
          </a>

          <!-- toggle button -->

          <button
            class="navbar-toggler"
            type="button"
            data-toggle="collapse"
            data-target="#navbarToggle"
            aria-controls="navbarToggle"
            aria-expanded="false"
            aria-label="Toggle navigation"
          >
            <span class="navbar-toggler-icon"></span>
          </button>

          <!-- Navigation togglers -->
          <div class="collapse navbar-collapse" id="navbarToggle">
            <div class="navbar-nav mr-auto" id="navbar-buttons">
              <a class="nav-item nav-link" href="{{ url_for('main.home') }}">
                <button>Home</button>
              </a>
              <a class="nav-item nav-link" href="{{ url_for('main.about') }}">
                <button>About</button>
              </a>
            </div>

            <div class="navbar-nav" id="navbar-buttons">
              <!-- If user is authenticated i.e. logged in  -->

              {% if current_user.is_authenticated %}
              <a
                class="nav-item nav-link"
                href="{{ url_for('posts.new_post') }}"
                ><button>New Post</button></a
              >
              <a class="nav-item nav-link" href="{{ url_for('users.account') }}"
                ><button>Account</button></a
              >
              <a class="nav-item nav-link" href="{{ url_for('users.logout') }}"
                ><button>Logout</button></a
              >

              <!-- else -->

              {% else %}
              <a class="nav-item nav-link" href="{{ url_for('users.login') }}"
                ><button>Login</button></a
              >
              <a
                class="nav-item nav-link"
                href="{{ url_for('users.register') }}"
                ><button>Register</button></a
              >
              {% endif %}
            </div>
          </div>
        </div>
      </nav>
    </header>
    <main role="main" class="container">
      <div class="row">
        <div class="col-md-8">
          {% with messages = get_flashed_messages(with_categories=true) %}

          <!-- if found flash msgs display them -->

          {% if messages %} {% for category, message in messages %}
          <div class="alert alert-{{ category }}">{{ message }}</div>
          {% endfor %} {% endif %} {% endwith %} {% block content %}{% endblock
          %}
        </div>

        <!-- SideBar -->

        <div class="col-md-4">
          <div
            class="content-section mt-4 ml-3"
            style="background-color: rgb(182, 238, 233)"
          >
            <h4>Check out what's humming!</h4>
            <p class="text-muted">This is your own world .</p>
            <ul class="list-group">
              <li
                class="list-group-item list-group-item-light"
                style="
                  background-color: rgb(36, 209, 195);
                  font-size: 1.2em;
                  color: rgb(255, 255, 255);
                  padding: 0.7em 0.4em;
                "
              >
                <a href="{{url_for('main.latest_post')}} ">Latest Posts</a>
              </li>
              <li
                class="list-group-item list-group-item-light"
                style="
                  background-color: rgb(36, 209, 195);
                  font-size: 1.2em;
                  color: rgb(255, 255, 255);
                  padding: 0.7em 0.4em;
                "
              >
                <a href="{{url_for('main.announcements')}} ">Announcements</a>
              </li>
              <li
                class="list-group-item list-group-item-light"
                style="
                  background-color: rgb(36, 209, 195);
                  font-size: 1.2em;
                  color: rgb(255, 255, 255);
                  padding: 0.7em 0.4em;
                "
              >
                <a href="{{url_for('main.calendar')}} ">Calendars</a>
              </li>
            </ul>
          </div>
        </div>
      </div>
    </main>
    <!-- Optional JavaScript -->
    <!-- jQuery first, then Popper.js, then Bootstrap JS -->

    <script
      src="https://code.jquery.com/jquery-3.2.1.slim.min.js"
      integrity="sha384-KJ3o2DKtIkvYIK3UENzmM7KCkRr/rE9/Qpg6aAZGJwFDMVNA/GpGFF93hXpG5KkN"
      crossorigin="anonymous"
    ></script>
    <script
      src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.12.9/umd/popper.min.js"
      integrity="sha384-ApNbgh9B+Y1QKtv3Rn7W3mgPxhU9K/ScQsAP7hUibX39j7fakFPskvXusvfa0b4Q"
      crossorigin="anonymous"
    ></script>
    <script
      src="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0/js/bootstrap.min.js"
      integrity="sha384-JZR6Spejh4U02d8jOt6vLEHfe/JQGiRRSQQxSfFWpi1MquVdAyjUar5+76PVCmYl"
      crossorigin="anonymous"
    ></script>
  </body>
</html>

FlaskBlog/flaskblog/templates/post.html
<!-- 
    post.html
    Inherits the properties from the template -- layout.html
    This is template to render the posts of the users 
    in the format as title followed by content with date on which the content was 
    posted to the site.
-->

{% extends "layout.html" %} {% block content %}
<article
  class="media content-section mt-4 ml-0 mr-0"
  style="background-color: rgb(255, 255, 255)"
>
  <!-- profile img of the user -->

  <img
    src="{{ url_for('static', filename='profile_pics/'+post.author.image_file) }}"
    alt="profile-image"
    class="rounded-circle article-img"
  />

  <div class="media-body">
    <div class="article-metadata">
      <a
        class="mr-2"
        href=" {{url_for('users.user_posts', username = post.author.username)}} "
        >{{ post.author.username }}</a
      >
      <small class="text-muted"
        >{{ post.date_posted.strftime('%Y-%m-%d') }}</small
      >

      <!-- giving previledges to modify the post if the user is the author -->

      {% if post.author == current_user %}
      <div>
        <a
          class="btn btn-secondary btn-sm mt-1 mb-1"
          href="{{url_for('posts.update_post', post_id = post.id)}}"
          >Update</a
        >
        <button
          type="button"
          class="btn btn-danger btn-sm m-1"
          data-toggle="modal"
          data-target="#deleteModal"
        >
          Delete
        </button>
      </div>
      {% endif%}
    </div>

    <!-- title of the post followed by the contents -->
    <h2 class="article-title">{{ post.title }}</h2>
    <p class="article-content">{{ post.content }}</p>
  </div>
</article>

<!-- Modal to confirm the deletion of the post-->

<div
  class="modal fade"
  id="deleteModal"
  tabindex="-1"
  role="dialog"
  aria-labelledby="deleteModalLabel"
  aria-hidden="true"
>
  <div class="modal-dialog" role="document">
    <div class="modal-content">
      <!-- Header -->

      <div class="modal-header">
        <!-- legend to ask for confirmation -->
        <h5 class="modal-title" id="deleteModalLabel">Delete Post?</h5>

        <button
          type="button"
          class="close"
          data-dismiss="modal"
          aria-label="Close"
        >
          <span aria-hidden="true">&times;</span>
        </button>
      </div>

      <!-- Footer -->

      <div class="modal-footer">
        <button type="button" class="btn btn-secondary" data-dismiss="modal">
          Close
        </button>
        <form
          action="{{ url_for('posts.delete_post', post_id=post.id) }}"
          method="POST"
        >
          <input class="btn btn-danger" type="submit" value="Delete" />
        </form>
      </div>
    </div>
  </div>
</div>
{% endblock content %}